export const GET_QUIZ_QA = "GET_QUIZ_QA";
export const SET_QUIZ_QA = "SET_QUIZ_QA";

export const VALIDATE_ANSWER = "VALIDATE_ANSWER";

export const CALCULATE_PARTIAL_SCORE = "CALCULATE_PARTIAL_SCORE";
